server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/society_management_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: idiot_Yuqn@123
    #druid配置
    druid:
      #初始化大小
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      #获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      #是否开启PSCache,PSCahce对支持游标的数据库性能提示巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      #开启poolPreparedStatments后生效
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  activiti:
    # 1、flase：默认值。activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    # 2、true：activiti会对数据库中所有表进行更新操作，如果表不存在，则自动创建
    # 3、create_drop：在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    # 4、drop-create：在activiti启动时删除原来的旧表，然后再创建新表（不需要手动关闭引擎）
    database-schema-update: flase
    # activiti7 默认不生成历史信息表，开启历史表
    db-history-used: true
    # 记录历史等级 可配置的历史级别有none，activity，audit，ful1
    # none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    # activity：级别高于none，保存流程实例与流程行为，其他数据不存。
    # audit：除aetivity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
    # full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full
    async-executor-activate: false
#mybatisplus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
